name: Inject API Key

on:
  push:
    branches:
      - main

jobs:
  inject-api-key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug Git
      run: |
        git config --global --add safe.directory /github/workspace
        git remote -v
        git branch -a

    - name: Replace API key in HTML
      run: |
        sed 's/{API_KEY}/${{ secrets.API_KEY }}/g' index.html > index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
